### ISSUE TITLE
Help identifying component L1.

### ISSUE THREAD

**Issue by walkere** [David00/rpi-power-monitor#12]
The L1 component in the schematic just says 1m with no units. Package type 0.4 axial. I looked at the assembled board picture. I want to check my assumptions. Is that a high frequency ferrite choke?

**Comment by David00** [comment]
Hi @walkere, I will label this as a documentation issue. L1 was _intended_ to be a small inductor to assist with cleaning up the 3.3V supply, but it ended up not being needed. A future version of the PCB and schematic will have this component removed.  If you have a board with the L1 component on it already, you can simply use a small wire link.

**Comment by walkere** [comment]
Thank you.
