### ISSUE TITLE
Config files enhancements

### ISSUE THREAD

**Issue by richie256** [David00/rpi-power-monitor#22]
Here is some idea of improvement I would suggest to implement:

- Friendly name / Alias name for a specific CT in config file.

- Enable - Disable for each CT in config file -- do not perform calculation for CT not enabled.

- Consumption or Production Value for each CT.

- Dynamically calculate the Net production, etc. based on values in config file.

**Comment by David00** [comment]
Hi richie256, thanks for the suggestions! I'm actually planning some of these for a future major software version, so stay tuned!

Regarding the consumption/production for each CT: the individual instantaneous power measurements are already stored in the DB, so you can have Grafana calculate the total consumption/production amount by integrating the curve that the instantaneous values produce.  Some of the stat figures in the default dashboard do this, and there's also an alternative dashboard that shows this. Check out the [Dashboard page](https://github.com/David00/rpi-power-monitor/wiki/Software-3.-Building-your-Dashboard) in the wiki.

I'm going to close this issue but feel free to add more comments if you think of anything else you'd like to see!
