### ISSUE TITLE
event analyser

### ISSUE THREAD

**Issue by BjornFallman** [David00/rpi-power-monitor#23]
I just found this project, and finds it very interesting. I have not read all the documentation, so this might be an obsolete question.

Have you considered any event recorder, for analysis of voltage sags (duration and magnitude) in ms time scale?

**Comment by David00** [comment]
Hi Bjorn, I've considered that but chosen not to implement it. All of the measurements are taken and calculated based on data samples that take approximately 500ms - 700ms to capture. We capture about 2000 samples on each channel in that short time frame and calculate the real power using the individual sample points, but the voltage level is actually an RMS calculation.

The RMS voltage level is stored in Grafana, so you could in theory setup an alert in Grafana's dashboard directly to notify you in the event of voltage abnormalities. But, given the relatively large snapshot window and the configurable, but default [two-point average](https://github.com/David00/rpi-power-monitor/blob/master/power-monitor.py#L486) that averages two adjacent readings prior to storing, I don't think you'd get quite the granularity that you're talking about.

With these points, I consider event analysis out of the scope of the current project. I will close the issue with this comment, but feel free to continue discussion if you'd like!
