### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by wizbandit** [David00/rpi-power-monitor#24]
Upgrade the python-apt packages. For the stable distribution (buster), this problem has been fixed in version 1.8.4.2.
new ver 12/20/20

**Comment by David00** [comment]
Thanks. There were actually quite a few unnecessary imports (including python-apt) in the requirements.txt file. I've cleaned up the requirements.txt file with only the necessary libraries. Pip will handle installing the individual libraries' dependencies.
