### ISSUE TITLE
Suggestion: Channel Input Board 

### ISSUE THREAD

**Issue by dotbanana** [David00/rpi-power-monitor#32]
I found this interesting project here which resembles something quite similar but with
the additional functionality of monitoring every circuit seperately because of more possible inputs.  
You can then monitor after every fuse seperately and make statistics for every room in the house.  
Maybe it would be an idea to make something similar as voluntary upgrade which is compatible software and hardware-wise to your project:   
https://github.com/crjens/PiPowerMeter

Image: https://github.com/crjens/PiPowerMeter/blob/master/Documentation/DSC_0009.JPG

**Comment by David00** [comment]
That's very cool looking. Thanks for sharing. I am looking at expanding the number of inputs for my project in a future hardware revision, so stay tuned!
