### ISSUE TITLE
Phase calibration does not work even with the correct kernel version

### ISSUE THREAD

**Issue by chenhoulin6204** [David00/rpi-power-monitor#45]
So, I've followed the setup instructions, the only difference is I remade the circuit on a breadboard and used some bigger capacitors.
The current transformer I used is YHDC SCT006, the burden resistor is 22 Ohms.

The issue is, when I am doing the phase calibration, even with the correct kernel version (4.19.118-v7l+), the results are still larger than 1.x. I have attached the results from your program's debug mode and phase calibration mode, please help!
(The sampling rate reported by the debug mode is around 28 KSPS, is that normal? I don't know... I am using Raspberry Pi 4B with 4GB ram)
[phase_calibration_problem.zip](https://github.com/David00/rpi-power-monitor/files/8029266/phase_calibration_problem.zip)

The load I used was an electric heater and its power factor is 1.00, confirmed by a store-bought power meter.

I have also attached photos of my setup, I am clueless what to do next... Any help is much appreciated, thanks a lot.
![IMG_3670](https://user-images.githubusercontent.com/55968144/153119830-fab47609-db75-4770-83f3-28f1871fe0cb.jpg)
![IMG_3666](https://user-images.githubusercontent.com/55968144/153119836-461006b4-f181-4b76-bef7-ff3c7c5246f4.jpg)

**Comment by chenhoulin6204** [comment]
Hi,

1. The R0 is here:

I am only using one CT, so R1-R3, R8-R9 are not connected. R0 is at 22Ohms. The LMV321 is outputting 1.65V but my problem was I connected one of the CT’s feet to GND, I have now correctly connected it to the Vbias.
2. I’ve used a load resistor to make the AC input now 10V, but it is still not working well. R4 is 9.9k and R5 is 99.8k Ohms as measured so I think the values are correct, but when I measure the AC voltage between R4 R5 and GND, I got 0V instead of the expected 1V, I suspect either the ADC is drawing too much current or something wrong with the GND_break? I am currently using a 4.7µF electrolytic capacitor to ground it to GND.

The problem now has changed, the phase calibration does not give me 2.x anymore but the results are inconsistent, the value fluctuates. Also in terminal mode, the unconnected CTs are showing weird results, although I am able to complete the accuracy calibration now, something still seems wrong. I’ve attached the updated initial test and phase calibration results, could you take a look please? Thanks a lot for your time!

Sent from Mail for Windows

**Comment by David00** [comment]
Can you add the attachments on GitHub directly? They don't come through via email.

> The problem now has changed, the phase calibration does not give me 2.x anymore but the results are inconsistent, the value fluctuates. Also in terminal mode, the unconnected CTs are showing weird results, although I am able to complete the accuracy calibration now, something still seems wrong.

Don't worry about the values until the circuitry is fixed.  You'll still be very susceptible to noise on the breadboard though, and you can already see that noise in the original debug plot on the other CT channels that you don't have connected to anything.  Not much you can do about that on a breadboard.

**Comment by chenhoulin6204** [comment]
Hi, sorry for the delay. I can complete the accuracy calibration now, but I still think the results are dodgy, since the phase calibration value is inconsistent.

The debug test result and phase calibration result are attached, what could be the problem please? Is it because of the noise? Could using shorter cables or better cables solve this problem? Or is it the capacitors I used are of poor quality? I have no idea...

Please educate me, thanks a lot
[new_results.zip](https://github.com/David00/rpi-power-monitor/files/8094113/new_results.zip)
!

**Comment by David00** [comment]
The new `initial_test.html` looks pretty good now actually.  The only thing I'd recommend is trying with a higher powered resisitve load so that the current samples coming in are more in the middle of the range of the sensor.

If you don't have a larger resistive load, you can use the loop trick to multiple the amount of current that the sensor sees:
https://github.com/David00/rpi-power-monitor/wiki/Phase-Correction-Procedure#current-multiplication-example
