### ISSUE TITLE
Docker images wont start

### ISSUE THREAD

**Issue by mnh637** [David00/rpi-power-monitor#46]
Hi,
I've tried both the image and installing from scratch (on bullseye) but when i do docker ps status is always restarting.
239e96bd1c45   influxdb:1.8.3          "/entrypoint.sh infl…"   3 hours ago   Restarting (139) 17 seconds ago             influx
8a945ecb7074   grafana/grafana:7.3.7   "/run.sh"                3 hours ago   Restarting (139) 13 seconds ago             grafana

I'm on a Pi zero, hoping you  can help

Thanks
Mark

**Comment by David00** [comment]
Hi, please try again with a Pi 3B+ or newer. The Pi Zero is not supported.

**Comment by mnh637** [comment]
Thank you will give it a go :-)

**Comment by mnh637** [comment]
Thanks, tried on a pi 4 and it's all happy :-) Thanks Again. Mark

**Comment by David00** [comment]
Great!
