### ISSUE TITLE
v0.2.0 No OS Image

### ISSUE THREAD

**Issue by emersonsc** [David00/rpi-power-monitor#73]
There is currently no OS image with the v0.2.0 release. Would someone who's starting this project just go ahead with the old image or is it better to wait for the updated custom OS image to be released?

**Comment by David00** [comment]
I had problems getting the OS image added to the v0.2.0 release assets - I guess there are new file size restrictions preventing large files in releases.

The OS image is hosted in the branch titled release-v0.2.0

https://github.com/David00/rpi-power-monitor/tree/release-v0.2.0

[Direct image link](https://github.com/David00/rpi-power-monitor/blob/release-v0.2.0/Raspberry-Pi-OS-Lite_rpi_power_monitor-0.2.0%2Brelease.zip)

I would recommend using this image over the v0.1.0 one.
