### ISSUE TITLE
Case/Enclosure

### ISSUE THREAD

**Issue by emersonsc** [David00/rpi-power-monitor#74]
Have you or anyone shared a design/stl for a 3d printed case That will work with a 3b+ or 4b and the original style board with the RJ45 jack?

**Comment by David00** [comment]
Yep! I have case designs for both the 3B+ and the 4B for the original DIY board that you assemble yourself.  The STLs are attached.

[Pi 3B+ - With Fan Hole Top.zip](https://github.com/David00/rpi-power-monitor/files/10094334/Pi.3B%2B.-.With.Fan.Hole.Top.zip)


[Power Mon Case - Pi 4.zip](https://github.com/David00/rpi-power-monitor/files/10094336/Power.Mon.Case.-.Pi.4.zip)
