### ISSUE TITLE
"database not found" when starting power-monitor.py

### ISSUE THREAD

**Issue by nickcmeyer** [David00/rpi-power-monitor#8]
Hello,

Everything seems to have gone well when installing according to the wiki. I did have to start the Docker containers manually after restart because they did not start on their own.

When trying to run power-monitor.py I get the following exception for, "Database not found". Can you tell where I went wrong?

![image](https://user-images.githubusercontent.com/49877497/89134021-0a167800-d4e7-11ea-8b45-7969c28acd72.png)

**Comment by David00** [comment]
Nick, thanks for opening an issue on this. Someone else also pointed it out to me via email earlier today. I will fix this shortly with an update, but for now, simply start the software regularly with:

    python3 power-monitor.py

After a few seconds, stop it with Ctrl-c.  Then, you will be able to start it in terminal mode.
