### ISSUE TITLE
Voltage Tuning

### ISSUE THREAD

**Issue by atzimot** [David00/rpi-power-monitor#81]
I'm tring to do the voltage tuning and i have in terminal values below 0

GRID_VOLTAGE = 235
AC_TRANSFORMER_OUTPUT_VOLTAGE = 8.94

What do I have to do ?
I have done all steps from the wiki

![image](https://user-images.githubusercontent.com/4029868/206446370-7037de32-ae04-47ff-8451-5813f1269d32.png)

**Comment by David00** [comment]
Hi atzimot, is this from a DIY board or the factory assembled PCB?

Can you run and attach the output from a debug plot?
https://github.com/David00/rpi-power-monitor/wiki/Software-1.-Overview#debug-mode

Also, make sure that the software is not running in the background with `sudo systemctl status power-monitor`, and if it is running, stop it with `sudo systemctl stop power-monitor`.

**Comment by atzimot** [comment]
Hi David,
  Is a factory  assembled PCB.
  The service was stopped when I have done the tuning.
  I have attached the debug plot
 I don't have any ct attached right now to the PBC

![image](https://user-images.githubusercontent.com/4029868/206641696-0fece175-1576-4a1e-bd70-99b7004c1e33.png)

**Comment by atzimot** [comment]
also I have used your prebuild raspbbery image

**Comment by emersonsc** [comment]
Have you only done the initial voltage check and input for the voltage, or have you changed other values in the config.py? 

Also, after you changed the values in config.py, did you run the following:
 cd ~/rpi_power_monitor
 pip install .

lastly, can you copy and paste the contents of your config.py

**Comment by David00** [comment]
@ atzimot, was your AC power supply plugged into the PCB when you ran the debug plot above? The PCB looks like it is not seeing much come in on the AC voltage input.  Can you share a photo of the label on the AC power supply that you're using?

**Comment by atzimot** [comment]
I have changed the AC power supply and now the debug is like this.
Now the AC has the value 9.54V 

![image](https://user-images.githubusercontent.com/4029868/206838064-ac781b3d-836f-481e-b1ab-b671f6eceb4b.png)

Here is the AC data

![image](https://user-images.githubusercontent.com/4029868/206838085-df057717-22a3-4ee4-9014-932fb9c916f9.png)

But the values are the same under 0

![image](https://user-images.githubusercontent.com/4029868/206838104-ed4c4704-b588-4102-8123-bec5b01858b5.png)

**Comment by David00** [comment]
The problem appears to be that your power supply puts out 9V DC, not 9V AC.  It needs to be an AC output.

**Comment by atzimot** [comment]
Thanks for the info
What is the minimum consumtion for this transformer ?
I'm asking becuase I have found transformers but they have different consumtions 100, 200, 400 mA

**Comment by emersonsc** [comment]
Jameco Reliapro 9V AC to AC
Output: 9V AC, 500mA

**Comment by David00** [comment]
> What is the minimum consumtion for this transformer ?

Any of the ones you've listed should work fine. There is very little consumption from the AC transformer input.
