### ISSUE TITLE
Which urllib3 version?

### ISSUE THREAD

**Issue by nightcustard** [David00/rpi-power-monitor#98]
Hi David

I've just upgraded from v0.2.0 to v0.3.0, having previously installed influxdb_client.  The upgrade uninstalled urllib3 1.26.15 and installed urllib3 1.24.3 in its place (to be compatible with requests 2.21.0).  Unfortunately influxdb_client requires version 1.26.15

I subsequently reinstalled influxdb_client, which in turn reinstalled urllib3 1.26.15 

power_monitor v0.3.0 still seems to work OK though I presume I've broken some functionality (using requests) which I haven't found yet(!)  Can you please advise?

Cheers, Mike

**Comment by David00** [comment]
That should all be fine as this project doesn't make use of `urllib`.  So, as long as the `influxdb_client` dependencies are happy, your power monitor will be happy.
